### ISSUE TITLE
View 100 - Shareable camera position

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#1043]
As a user I want to share a link to my current project location, including camera, cutplanes, element visibility and selection.

# Tasks
* User visits homepage, positions camera, clicks ShareControl
    - [ ] ShareDialog opens - Screen
      - [ ] QR code
      - [ ] Input box containing the link
      - [ ] Toggle for including the camera view
      - [ ] Button to copy the link
      * Toggle camera
        - [ ] Removes and adds camera from link
      * Click Share button
        - [ ] Link copied to clipboard
* User visits copied link
  - [ ] Sees save view
  
# Tests
[Cypress](https://github.com/bldrs-ai/Share/blob/main/cypress/e2e/view-100/shareable-camera-position.cy.js)
[Percy](https://percy.io/8fe2b2f1/share/builds/33726545)
