### ISSUE TITLE
Profile 100: Login

### ISSUE THREAD

**Issue by nickcastel50** [bldrs-ai/Share#1052]
User should be able to pick a day or night theme for Share

# Tasks
* Returning user visits homepage
  * Click ProfileControl
    * Click GitHub Login
      - [ ] Login call performed
      - [ ] User's avatar visible - Screen
      - [ ] Logout item visible
      
# Tests
[Cypress](https://github.com/bldrs-ai/Share/blob/main/cypress/e2e/profile-100/login.cy.js)
