### ISSUE TITLE
Notes 100 - Access Notes list

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1054]
As a user, I want to access a list of the notes I've previously made so that I can review the additional information or comments that project team members have added to the model.

This feature enables me to:

- Browse through a list of all the extra details or issues I've noted on the model.

**Tasks:**

*Critical path:*
- [ ] **Action:** Find a note icon in the operations group
- [ ] **Action:** Click on the note icon in the operations group.
- [ ] **Expected Response:** A side drawer opens on the right side of the viewport (Desktop).
- [ ] **Expect:** A list of notes to be visible.
- [ ] **Expect:** The 'NOTES' title to be visible on the Navbar.

Secondary path:
- [ ] **Action:** 
- [ ] **Expected Response:**
- [ ] **Expect:**
