### ISSUE TITLE
Notes 100 - Note Contains link to Github issue

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1056]
As a user, I want the note to contain a link to a GitHub issue so that I can directly access the issue on GitHub if I opt to use GitHub tools for project management.

This feature allows me to:

- Access GitHub issue functionality by following a GitHub link.

**Tasks:**

*Critical path:*
- [x] **Action:** Find a note icon in the operations group
- [x] **Action:** Click on the note icon in the operations group.
- [x] *Expect:* The GitHub button to be visible.
- [x] **Action:** Find a note with a specific title.
- [x] **Action:** Click on a note with a specific title.
- [x] **Expected Response:** The list of notes is updated to display only the selected note.
- [x] *Expect:* The GitHub button to be visible.
