### ISSUE TITLE
Notes 100: Create a note

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1059]
As a user, I want to write a note and attach it to a specific part of the 3D model so that I can have discussions about it or add more information to the element.

This feature enables me to:

- Add additional details directly to the model.

# Tasks
  * User visits homepage in the logged-in state 
     -  Click on the note control > Click on the 'Add a Note' control
          - [ ] Notes list switched to display only create note card SCREEN
          - [ ] Back button navigates to the notes list
        1) Type in note title and note body > click submit button
             - [ ] Enable submit button then the note is filled
             - [ ] Navigate to the notes list when the note is submitted
             - [ ] Show the new note at the top of the list ---> TODO(oleg): the final check with the created note appended to the top of the list will be implemented when Pablo finished the github store mock
# Tests
[Cypress]()
[Percy](https://percy.io/8fe2b2f1/share/builds/34012444)

**Comment by OlegMoshkovich** [comment]
https://github.com/bldrs-ai/Share/pull/1148
working on this PR to get it setup for edit notes and create notes
