### ISSUE TITLE
Profile 100 - Theme

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#1070]
User should be able to change from day to night theme.

# Tasks
* Returning user visits homepage
  - [x] Day theme active - Screen
  * Select ProfileControl > Night theme
    - [x] Night theme active - Screen
    * Select ProfileControl > Day theme
      - [x] Day theme active - Screen
# Tests
[Cypress](https://github.com/bldrs-ai/Share/blob/main/cypress/e2e/profile-100/theme.cy.js)
[Percy](https://percy.io/8fe2b2f1/share/builds/33707503)

**Comment by OlegMoshkovich** [comment]
Can you please follow this convention for the issues:

As a user i want to ... , so that I can ... .

This feature enables me to:
...

Critical path:
- [ ] **Action:** ...
- [ ] **Expected Response:** ...
- [ ] **Expect:** ...

Secondary path:
- [ ] **Action:** ...
- [ ] **Expected Response:** ...
- [ ] **Expect:** ...

**Comment by pablo-mayrgundter** [comment]
Still a WIP.. here's current format after our convo yesterday

https://github.com/bldrs-ai/Share/issues/1031
