### ISSUE TITLE
Notes 100: Share a note

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1071]
As a user I want to share a note via link, so that I can quickly get project contributor on the same page.

# Tasks
* Visit model as returning user
  * Open notes, select first
    * Click on the share button on the footer of the note
      - [x] Link written to clipboard
      - [x] SnackBar informs link copied - Screen
      - [x] Link has model path, issue id, current camera
      - [x] SnackBar disappears automatically
