### ISSUE TITLE
Notes 100 - Access shared note

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1072]
As a user, I want to access the notes shared with me via the link so that I can see the information and the 3d model view of the project.

# Tasks
    
  * Access the shared link containing the path to the general notes
    - [x] Correct project to be loaded into the viewport and side drawer to be open - Screen
      - [x] Panel title to contain 'NOTES' string
      - [x] List of notes to be visible
  * Access the shared link containing the path to a note index
    - [x] Correct project to be loaded into the viewport and side drawer to be open - Screen
      - [x] Panel title to contain 'NOTE' string
      - [x] Panel nav to contain back button
      - [x] Shared note to be visible 
      - [x] Notes comments to be visible
  

# Tests
[Cypress](https://github.com/bldrs-ai/Share/blob/main/cypress/e2e/notes-100/access-shared-note.cy.js)
[Percy](https://percy.io/8fe2b2f1/share/builds/33846447/changed/1853375510)
