### ISSUE TITLE
Create 100 - Imagine

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#1077]
As a user, I want to leverage AI technology to quickly produce high-quality renderings based on keyword descriptions.

# Tasks
* View model
  * Click ImagineControlButton
    - [x] Dialog with screenshot - Screen
    * Enter description "candy cane", click Create
      - [ ] Shows candy cane render -  Screen
      * Reopen dialog
        - [ ] Shows screenshot - Screen
# Tests
[Cypress]()
[Percy](https://percy.io/8fe2b2f1/share/builds/33655124)
