### ISSUE TITLE
View 100 - Cutplanes

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#1106]
As as user I want to add cutplanes to the model view to expose internals.

The cutplanes are:
- Plan (y-axis)
- Section (x-axis)
- Elevation (z-axis)

# Tasks
* View model (see [Initial model load and view](https://github.com/bldrs-ai/Share/issues/1031))
  * Click CutPlaneControl
    - [x] Section menu visible - Screen
    * Select all cut-planes
      - [x] All cut-planes added to model - Screen
    * Clear all cut-planes
      - [x] No cut-planes visible - Screen
* View cut-plane permalink
  - [x] Shows just vertical bar of b - Screen
* All hidable controls visible
  - [x] Clearing cut-planes leaves other page state alone - Screen
* View cut-plane permalink with camera - TODO(pablo): can't mouse drag in cypress
  * Add cutplane, then move model
    - [ ] Camera repositioned - Screen
    * Clear cutplane
      - [ ] Camera position unchanged - Screen

# Tests
[Cypress](https://github.com/bldrs-ai/Share/blob/main/cypress/e2e/view-100/cutplanes.cy.js)
[Percy](https://percy.io/8fe2b2f1/share/builds/33650360/changed/1843635895)
