### ISSUE TITLE
Open 200: Tabbed Open dialog

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1190]
As a user, when accessing BLDRS and choosing to open a model, I would like to be taken to a tabbed open dialog with a clear list of sample models in a separate sample tab, each with a button representing the path to the sample model. 
In a separate projects tab, I would like to access functionality to open a model from my local machine, along with sample text explaining how Share works with GitHub.
In the logged-in state, I would like to have access to my GitHub account and be provided controls to choose an organization, repository, folder, and path to the file.

# Tasks
* First-time user visits homepage not logged in
  * Access Open Dialog
    - [ ] Sample tab to be selected and Momentum sample model chip to be visible - Screen
  * Select Projects tab
    - [ ] Open button is visible and please login message to the visible - Screen
    - [ ] Press open the model -> file browser is open
        * Login to Share
        - [ ] GitHub controls are visible - Screen
        - [ ] Choose the path to the model on GitHub -> model is loaded into the scene - Screen

[figma](https://www.figma.com/design/DqKVaQEukf8vVHnlwiRGhv/Share-Screens?node-id=2723-23&t=pxFPWR8SkKHWEi4k-0)
[percy](https://percy.io/8fe2b2f1/share/builds/34341993)

**Comment by OlegMoshkovich** [comment]
<img width="1395" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/cdd69e03-e546-4744-b44f-685e08149f54">

Getting these error, if schep is loaded, this error start to appear and after it every attempt to load a model results in the same error.

**Comment by OlegMoshkovich** [comment]
if I login everything appears to be ok
<img width="1372" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/ac7bb25a-1283-48e8-b9a9-52ad312c026c">

**Comment by OlegMoshkovich** [comment]
<img width="1380" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/eeda8595-c141-4a0b-b67e-e3d2018671c9">


when trying to load on of the test models I get this error.
