### ISSUE TITLE
Apps 100: Browse apps and select app

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#1282]
As a user, I want to browse available apps and select an app that adds capabilities to Share.

# Tasks
* Returning user visits homepage
  - [x] Apps button should be present
  - [x] AppsDrawer should not be present
  * User clicks Apps button
    - [x] should show AppsDrawer
    * User selects ExampleApp
      - [x] should show AppPanel
