### ISSUE TITLE
System: Register new domain

### ISSUE THREAD

**Issue by oogali** [bldrs-ai/Share#220]
Currently, the project is published to the web via Github pages using the `bldrs.ai` domain.

To validate other deployment options in a live environment, another domain is needed to perform side-by-side testing between the existing deployment model and any new candidate models.

### Tasks

- [x] Register `bldrs.dev`
- [x] Transfer domain to official BLDRS ownership (and registrar)
- [x] Define DNS record to reject receipt of mail with this domain
