### ISSUE TITLE
Connect Netlify

### ISSUE THREAD

**Issue by oogali** [bldrs-ai/Share#222]
### Tasks

- [x] Create a new site and connect to bldrs-ai/Share repository
- [x] Add `bldrs.dev` and update DNS name servers
- [x] Enable automatic TLS certificate generation via Let's Encrypt
- [x] Configure automatic deployment of production branches
- [x] Configure deploy previews

**Comment by oogali** [comment]
Transferred existing site to bldrs Netlify account.
