### ISSUE TITLE
UX: Show New Project

### ISSUE THREAD

**Issue by nickcastel50** [bldrs-ai/Share#737]
URL changes, empty space shown, share button enabled

Also:
- [ ] bldrs-ai/Share#738
- [ ] bldrs-ai/Share#740
- [ ] bldrs-ai/Share#741
