### ISSUE TITLE
Notes 100: Comments on a note

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#978]
As a user, I want to be able to leave comments on notes so that I can engage in discussions with the project team regarding the topics of the issues.

**This feature will enable me to:**
This feature will enable me to enhance the details associated with the model element by providing additional information.

# Tasks
  
  * User visits homepage
     -  Click on the note control > access a note with a specific title
          - [ ] Please login message to be visible
        1) User logs in
          - [ ] Create a comment card to be visible
        2) input the comment body and click submit
             - [ ] Created comment is appended below the comment create box ---> TODO(oleg): the final check will be implemented when Pablo finishes the GitHub store mock
