### ISSUE TITLE
Versions 100: Save model

### ISSUE THREAD

**Issue by nickcastel50** [bldrs-ai/Share#980]
As a user, I want the ability to save the model I've just loaded in a specific organization repository and a folder on Github, so that I can retrieve it later.

The conditions are:
- Save IFC button is not found before login
- Save IFC button is found only after login
- Save IFC button is clickable and the save action can be executed post-login

## Tasks

- **Visit homepage without model loaded**
  - [x] Check absence of Save IFC button pre-login
  - [x] Confirm presence of Save IFC button post-login

- **Save model action**
  - [x] Login, click Save IFC button, input details and save
---

[Cypress](https://github.com/bldrs-ai/Share/blob/ca1f3f717c5f2e9668cdd3b9a4db5bcaf0ec580b/cypress/e2e/versions-100/save-imported-model.cy.js)
[Percy](https://percy.io/8fe2b2f1/share/builds/33885913)

code:
- [x] MSW mocking of Auth0 service including Auth0Provider
